baseURL = "https://number317.github.io/blog/"
title = "cheon's blog"
theme = "aloha"
author = "cheon"
canonifyurls = true
uglyurls = false
languagecode = "en"
enableGitInfo = true
pygmentsCodefences = true
pygmentsUseClasses = false
#https://help.farbox.com/pygments.html
pygmentsStyle = "algol_nu"
pygmentsCodefencesGuessSyntax = true

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    sitename = "cheon's blog"
    description = "Aloha! Welcome to cheon's blog."
    disableWebFonts = false
    showSummary = false

[[menu.main]]
    name = "Home"
    url  = "https://number317.github.io"
    weight = 1
[[menu.main]]
    name = "Categories"
    url  = "/categories"
    weight = 2
[[menu.main]]
    name = "Tags"
    url  = "/tags"
    weight = 3
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/number317"
    weight = 4

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
